### ISSUE TITLE
*/UDP - UDP ports are used for the RTP screencast (the port is chosen dynamically by Janus).

### ISSUE THREAD

**Issue by keyanmca** [h-mdm/remote-control-android#14]
Is it possible to narrow down the ports used by Janus.  I mean specific ports.  due to security reasons its not advisable to open all the ports.  So pls suggest a better solution.

**Comment by h-mdm** [comment]
The default RTP port range is now 10000-10500. 

You can overrride this setting by adding the following variable in config.yaml:

rtp_port_range: 10100-10400

This will narrow the port range from 10000-10500 to 10100-10400.

**Comment by keyanmca** [comment]
Thank you Very Much for the immediate response and solution.. Thank you..
