### ISSUE TITLE
Unable to control Android phone

### ISSUE THREAD

**Issue by spatxos** [h-mdm/remote-control-android#16]
When I use https://github.com/h-mdm/remote-control and https://github.com/h-mdm/remote-control-android to compile and test, I can remotely display the operations on the Android phone. But I can't control it. What could be the reason?

![image](https://github.com/h-mdm/remote-control-android/assets/29770198/80d4b401-2fc5-4051-a70c-2188a860d012)

**Comment by h-mdm** [comment]
On some Android device models (we know about some TV boxes but probably some other devices too), Accessibility services do not work well: a device can't replay the gestures sent from the admin console. 

Unfortunately there's no solution for this issue by now, as this seems to be a firmware problem, sorry about that.

**Comment by spatxos** [comment]
I added an if judgment in the onRemoteControlEvent function of MainActivity.java and successfully controlled my Android phone.

```
     @Override
     public void onRemoteControlEvent(String event) {
         if (event.contains("home")) {
             Toast.makeText(this, "Control request received,"+event, Toast.LENGTH_LONG).show();
         }
         Intent intent = new Intent(MainActivity.this, GestureDispatchService.class);
         intent.setAction(Const.ACTION_GESTURE);
         intent.putExtra(Const.EXTRA_EVENT, event);
         startService(intent);
     }
```

What causes this? Is it because of the modified firmware Intent loading delay?

**Comment by spatxos** [comment]
You need to turn on USB debugging and other functions, then uninstall the app and reinstall the authorization, then you can control it remotely.

[Oppo手机如何开启USB调试](https://help.airdroid.com/hc/zh-cn/articles/360045675654-Oppo%E6%89%8B%E6%9C%BA%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AFUSB%E8%B0%83%E8%AF%95)
